//Cart Actions
export const ADD_GOODS_TO_CART = 'ADD_GOODS_TO_CART';
export const MODIFY_GOODS_NUM = 'MODIFY_GOODS_NUM';
export const DELETE_GOODS_ITEM = 'DELETE_GOODS_ITEM';
export const REQUEST_CART = 'REQUEST_CART';
export const RECEIVED_CART = 'RECEIVED_CART';

//Cover Actions
export const MODIFY_COVER_DIS = 'MODIFY_COVER_DIS';

//SourceList Actions
export const RECEIVED_SOURCE_LIST = 'RECEIVED_SOURCE_LIST';
export const FILTER_SOURCE_TYPE = 'FILTER_SOURCE_TYPE';


//Comment Actions
export const RECEIVED_COMMENT = 'RECEIVED_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const TOGGLE_PRAISE = 'TOGGLE_PRAISE';

//Everyday Actions
export const RECEIVED_EVERYDAY_LIST = 'RECEIVED_EVERYDAY_LIST';
export const RECEIVED_EVERYDAY_LIST_DATA = 'RECEIVED_EVERYDAY_LIST_DATA';
export const RECEIVED_EVERYDAY_LIST_REMOVE= 'RECEIVED_EVERYDAY_LIST_REMOVE';

//Slide Actions
export const RECEIVED_SLIDE_DATA = 'RECEIVED_SLIDE_DATA';

//Danpin Actions
// index
export const RECEIVED_BOOK_TYPE = "RECEIVED_BOOK_TYPE";
export const RECEIVED_BOOK_LIST = "RECEIVED_BOOK_LIST";
export const RECEIVED_SLIDER_LIST = "RECEIVED_SLIDER_LIST";
//detail
export const RECEIVED_BOOK_DETAIL = "RECEIVED_BOOK_DETAIL";
export const RECEIVED_BOOK_RELATED_LIST = "RECEIVED_BOOK_RELATED_LIST";

// Shop Actions
export const RECEIVED_PRODUCT_TYPE = 'RECEIVED_PRODUCT_TYPE';
export const RECEIVED_HOT_NEWS = 'RECEIVED_HOT_NEWS';
export const RECEIVED_PRODUCT_LIST = 'RECEIVED_PRODUCT_LIST';
